### ISSUE TITLE
查询失败

### ISSUE THREAD

**Issue by kennyNing** [xialeistudio/imooc-restful#1]
文章 all 查询
$sql = 'SELECT * FROM `article` WHERE `userId`=:userId ORDER BY `articleId` DESC LIMIT :offset,:limit';

我查询api.com/rest/articles?size=1 出不来数据，然后发现 :limit 这里的写法好像有问题编译ide 颜色都不对，不知道是不是这里有问题，麻烦确认下

**Comment by hewiez** [comment]
需要PDO预处理取消在本地模拟。
db.php中
`$pdo = new PDO('mysql:host=localhost;dbname=restful','root','root',[PDO::ATTR_EMULATE_PREPARES=>false]);
return $pdo;`

**Comment by hewiez** [comment]
PDO取消本地模拟。
db.php中
`$pdo = new PDO('mysql:host=localhost;dbname=restful','root','root',[PDO::ATTR_EMULATE_PREPARES=>false]);
return $pdo;`
